<?php
/**
 * Bangladeshi states (districts)
 */

if ( !defined( 'ABSPATH' ) ) {
    exit;
}

return array(
    'BAG'  => __( 'Bagerhat', WP_OFFICE_TEXT_DOMAIN ),
    'BAN'  => __( 'Bandarban', WP_OFFICE_TEXT_DOMAIN ),
    'BAR'  => __( 'Barguna', WP_OFFICE_TEXT_DOMAIN ),
    'BARI' => __( 'Barisal', WP_OFFICE_TEXT_DOMAIN ),
    'BHO'  => __( 'Bhola', WP_OFFICE_TEXT_DOMAIN ),
    'BOG'  => __( 'Bogra', WP_OFFICE_TEXT_DOMAIN ),
    'BRA'  => __( 'Brahmanbaria', WP_OFFICE_TEXT_DOMAIN ),
    'CHA'  => __( 'Chandpur', WP_OFFICE_TEXT_DOMAIN ),
    'CHI'  => __( 'Chittagong', WP_OFFICE_TEXT_DOMAIN ),
    'CHU'  => __( 'Chuadanga', WP_OFFICE_TEXT_DOMAIN ),
    'COM'  => __( 'Comilla', WP_OFFICE_TEXT_DOMAIN ),
    'COX'  => __( 'Cox\'s Bazar', WP_OFFICE_TEXT_DOMAIN ),
    'DHA'  => __( 'Dhaka', WP_OFFICE_TEXT_DOMAIN ),
    'DIN'  => __( 'Dinajpur', WP_OFFICE_TEXT_DOMAIN ),
    'FAR'  => __( 'Faridpur ', WP_OFFICE_TEXT_DOMAIN ),
    'FEN'  => __( 'Feni', WP_OFFICE_TEXT_DOMAIN ),
    'GAI'  => __( 'Gaibandha', WP_OFFICE_TEXT_DOMAIN ),
    'GAZI' => __( 'Gazipur', WP_OFFICE_TEXT_DOMAIN ),
    'GOP'  => __( 'Gopalganj', WP_OFFICE_TEXT_DOMAIN ),
    'HAB'  => __( 'Habiganj', WP_OFFICE_TEXT_DOMAIN ),
    'JAM'  => __( 'Jamalpur', WP_OFFICE_TEXT_DOMAIN ),
    'JES'  => __( 'Jessore', WP_OFFICE_TEXT_DOMAIN ),
    'JHA'  => __( 'Jhalokati', WP_OFFICE_TEXT_DOMAIN ),
    'JHE'  => __( 'Jhenaidah', WP_OFFICE_TEXT_DOMAIN ),
    'JOY'  => __( 'Joypurhat', WP_OFFICE_TEXT_DOMAIN ),
    'KHA'  => __( 'Khagrachhari', WP_OFFICE_TEXT_DOMAIN ),
    'KHU'  => __( 'Khulna', WP_OFFICE_TEXT_DOMAIN ),
    'KIS'  => __( 'Kishoreganj', WP_OFFICE_TEXT_DOMAIN ),
    'KUR'  => __( 'Kurigram', WP_OFFICE_TEXT_DOMAIN ),
    'KUS'  => __( 'Kushtia', WP_OFFICE_TEXT_DOMAIN ),
    'LAK'  => __( 'Lakshmipur', WP_OFFICE_TEXT_DOMAIN ),
    'LAL'  => __( 'Lalmonirhat', WP_OFFICE_TEXT_DOMAIN ),
    'MAD'  => __( 'Madaripur', WP_OFFICE_TEXT_DOMAIN ),
    'MAG'  => __( 'Magura', WP_OFFICE_TEXT_DOMAIN ),
    'MAN'  => __( 'Manikganj ', WP_OFFICE_TEXT_DOMAIN ),
    'MEH'  => __( 'Meherpur', WP_OFFICE_TEXT_DOMAIN ),
    'MOU'  => __( 'Moulvibazar', WP_OFFICE_TEXT_DOMAIN ),
    'MUN'  => __( 'Munshiganj', WP_OFFICE_TEXT_DOMAIN ),
    'MYM'  => __( 'Mymensingh', WP_OFFICE_TEXT_DOMAIN ),
    'NAO'  => __( 'Naogaon', WP_OFFICE_TEXT_DOMAIN ),
    'NAR'  => __( 'Narail', WP_OFFICE_TEXT_DOMAIN ),
    'NARG' => __( 'Narayanganj', WP_OFFICE_TEXT_DOMAIN ),
    'NARD' => __( 'Narsingdi', WP_OFFICE_TEXT_DOMAIN ),
    'NAT'  => __( 'Natore', WP_OFFICE_TEXT_DOMAIN ),
    'NAW'  => __( 'Nawabganj', WP_OFFICE_TEXT_DOMAIN ),
    'NET'  => __( 'Netrakona', WP_OFFICE_TEXT_DOMAIN ),
    'NIL'  => __( 'Nilphamari', WP_OFFICE_TEXT_DOMAIN ),
    'NOA'  => __( 'Noakhali', WP_OFFICE_TEXT_DOMAIN ),
    'PAB'  => __( 'Pabna', WP_OFFICE_TEXT_DOMAIN ),
    'PAN'  => __( 'Panchagarh', WP_OFFICE_TEXT_DOMAIN ),
    'PAT'  => __( 'Patuakhali', WP_OFFICE_TEXT_DOMAIN ),
    'PIR'  => __( 'Pirojpur', WP_OFFICE_TEXT_DOMAIN ),
    'RAJB' => __( 'Rajbari', WP_OFFICE_TEXT_DOMAIN ),
    'RAJ'  => __( 'Rajshahi', WP_OFFICE_TEXT_DOMAIN ),
    'RAN'  => __( 'Rangamati', WP_OFFICE_TEXT_DOMAIN ),
    'RANP' => __( 'Rangpur', WP_OFFICE_TEXT_DOMAIN ),
    'SAT'  => __( 'Satkhira', WP_OFFICE_TEXT_DOMAIN ),
    'SHA'  => __( 'Shariatpur', WP_OFFICE_TEXT_DOMAIN ),
    'SHE'  => __( 'Sherpur', WP_OFFICE_TEXT_DOMAIN ),
    'SIR'  => __( 'Sirajganj', WP_OFFICE_TEXT_DOMAIN ),
    'SUN'  => __( 'Sunamganj', WP_OFFICE_TEXT_DOMAIN ),
    'SYL'  => __( 'Sylhet', WP_OFFICE_TEXT_DOMAIN ),
    'TAN'  => __( 'Tangail', WP_OFFICE_TEXT_DOMAIN ),
    'THA'  => __( 'Thakurgaon', WP_OFFICE_TEXT_DOMAIN )
);
