<?php
/**
 * Philippines Provinces
 */

if ( !defined( 'ABSPATH' ) ) {
    exit;
}

return array(
    'ABR' => __( 'Abra', WP_OFFICE_TEXT_DOMAIN ),
    'AGN' => __( 'Agusan del Norte', WP_OFFICE_TEXT_DOMAIN ),
    'AGS' => __( 'Agusan del Sur', WP_OFFICE_TEXT_DOMAIN ),
    'AKL' => __( 'Aklan', WP_OFFICE_TEXT_DOMAIN ),
    'ALB' => __( 'Albay', WP_OFFICE_TEXT_DOMAIN ),
    'ANT' => __( 'Antique', WP_OFFICE_TEXT_DOMAIN ),
    'APA' => __( 'Apayao', WP_OFFICE_TEXT_DOMAIN ),
    'AUR' => __( 'Aurora', WP_OFFICE_TEXT_DOMAIN ),
    'BAS' => __( 'Basilan', WP_OFFICE_TEXT_DOMAIN ),
    'BAN' => __( 'Bataan', WP_OFFICE_TEXT_DOMAIN ),
    'BTN' => __( 'Batanes', WP_OFFICE_TEXT_DOMAIN ),
    'BTG' => __( 'Batangas', WP_OFFICE_TEXT_DOMAIN ),
    'BEN' => __( 'Benguet', WP_OFFICE_TEXT_DOMAIN ),
    'BIL' => __( 'Biliran', WP_OFFICE_TEXT_DOMAIN ),
    'BOH' => __( 'Bohol', WP_OFFICE_TEXT_DOMAIN ),
    'BUK' => __( 'Bukidnon', WP_OFFICE_TEXT_DOMAIN ),
    'BUL' => __( 'Bulacan', WP_OFFICE_TEXT_DOMAIN ),
    'CAG' => __( 'Cagayan', WP_OFFICE_TEXT_DOMAIN ),
    'CAN' => __( 'Camarines Norte', WP_OFFICE_TEXT_DOMAIN ),
    'CAS' => __( 'Camarines Sur', WP_OFFICE_TEXT_DOMAIN ),
    'CAM' => __( 'Camiguin', WP_OFFICE_TEXT_DOMAIN ),
    'CAP' => __( 'Capiz', WP_OFFICE_TEXT_DOMAIN ),
    'CAT' => __( 'Catanduanes', WP_OFFICE_TEXT_DOMAIN ),
    'CAV' => __( 'Cavite', WP_OFFICE_TEXT_DOMAIN ),
    'CEB' => __( 'Cebu', WP_OFFICE_TEXT_DOMAIN ),
    'COM' => __( 'Compostela Valley', WP_OFFICE_TEXT_DOMAIN ),
    'NCO' => __( 'Cotabato', WP_OFFICE_TEXT_DOMAIN ),
    'DAV' => __( 'Davao del Norte', WP_OFFICE_TEXT_DOMAIN ),
    'DAS' => __( 'Davao del Sur', WP_OFFICE_TEXT_DOMAIN ),
    'DAC' => __( 'Davao Occidental', WP_OFFICE_TEXT_DOMAIN ), // TODO: Needs to be updated when ISO code is assigned
    'DAO' => __( 'Davao Oriental', WP_OFFICE_TEXT_DOMAIN ),
    'DIN' => __( 'Dinagat Islands', WP_OFFICE_TEXT_DOMAIN ),
    'EAS' => __( 'Eastern Samar', WP_OFFICE_TEXT_DOMAIN ),
    'GUI' => __( 'Guimaras', WP_OFFICE_TEXT_DOMAIN ),
    'IFU' => __( 'Ifugao', WP_OFFICE_TEXT_DOMAIN ),
    'ILN' => __( 'Ilocos Norte', WP_OFFICE_TEXT_DOMAIN ),
    'ILS' => __( 'Ilocos Sur', WP_OFFICE_TEXT_DOMAIN ),
    'ILI' => __( 'Iloilo', WP_OFFICE_TEXT_DOMAIN ),
    'ISA' => __( 'Isabela', WP_OFFICE_TEXT_DOMAIN ),
    'KAL' => __( 'Kalinga', WP_OFFICE_TEXT_DOMAIN ),
    'LUN' => __( 'La Union', WP_OFFICE_TEXT_DOMAIN ),
    'LAG' => __( 'Laguna', WP_OFFICE_TEXT_DOMAIN ),
    'LAN' => __( 'Lanao del Norte', WP_OFFICE_TEXT_DOMAIN ),
    'LAS' => __( 'Lanao del Sur', WP_OFFICE_TEXT_DOMAIN ),
    'LEY' => __( 'Leyte', WP_OFFICE_TEXT_DOMAIN ),
    'MAG' => __( 'Maguindanao', WP_OFFICE_TEXT_DOMAIN ),
    'MAD' => __( 'Marinduque', WP_OFFICE_TEXT_DOMAIN ),
    'MAS' => __( 'Masbate', WP_OFFICE_TEXT_DOMAIN ),
    'MSC' => __( 'Misamis Occidental', WP_OFFICE_TEXT_DOMAIN ),
    'MSR' => __( 'Misamis Oriental', WP_OFFICE_TEXT_DOMAIN ),
    'MOU' => __( 'Mountain Province', WP_OFFICE_TEXT_DOMAIN ),
    'NEC' => __( 'Negros Occidental', WP_OFFICE_TEXT_DOMAIN ),
    'NER' => __( 'Negros Oriental', WP_OFFICE_TEXT_DOMAIN ),
    'NSA' => __( 'Northern Samar', WP_OFFICE_TEXT_DOMAIN ),
    'NUE' => __( 'Nueva Ecija', WP_OFFICE_TEXT_DOMAIN ),
    'NUV' => __( 'Nueva Vizcaya', WP_OFFICE_TEXT_DOMAIN ),
    'MDC' => __( 'Occidental Mindoro', WP_OFFICE_TEXT_DOMAIN ),
    'MDR' => __( 'Oriental Mindoro', WP_OFFICE_TEXT_DOMAIN ),
    'PLW' => __( 'Palawan', WP_OFFICE_TEXT_DOMAIN ),
    'PAM' => __( 'Pampanga', WP_OFFICE_TEXT_DOMAIN ),
    'PAN' => __( 'Pangasinan', WP_OFFICE_TEXT_DOMAIN ),
    'QUE' => __( 'Quezon', WP_OFFICE_TEXT_DOMAIN ),
    'QUI' => __( 'Quirino', WP_OFFICE_TEXT_DOMAIN ),
    'RIZ' => __( 'Rizal', WP_OFFICE_TEXT_DOMAIN ),
    'ROM' => __( 'Romblon', WP_OFFICE_TEXT_DOMAIN ),
    'WSA' => __( 'Samar', WP_OFFICE_TEXT_DOMAIN ),
    'SAR' => __( 'Sarangani', WP_OFFICE_TEXT_DOMAIN ),
    'SIQ' => __( 'Siquijor', WP_OFFICE_TEXT_DOMAIN ),
    'SOR' => __( 'Sorsogon', WP_OFFICE_TEXT_DOMAIN ),
    'SCO' => __( 'South Cotabato', WP_OFFICE_TEXT_DOMAIN ),
    'SLE' => __( 'Southern Leyte', WP_OFFICE_TEXT_DOMAIN ),
    'SUK' => __( 'Sultan Kudarat', WP_OFFICE_TEXT_DOMAIN ),
    'SLU' => __( 'Sulu', WP_OFFICE_TEXT_DOMAIN ),
    'SUN' => __( 'Surigao del Norte', WP_OFFICE_TEXT_DOMAIN ),
    'SUR' => __( 'Surigao del Sur', WP_OFFICE_TEXT_DOMAIN ),
    'TAR' => __( 'Tarlac', WP_OFFICE_TEXT_DOMAIN ),
    'TAW' => __( 'Tawi-Tawi', WP_OFFICE_TEXT_DOMAIN ),
    'ZMB' => __( 'Zambales', WP_OFFICE_TEXT_DOMAIN ),
    'ZAN' => __( 'Zamboanga del Norte', WP_OFFICE_TEXT_DOMAIN ),
    'ZAS' => __( 'Zamboanga del Sur', WP_OFFICE_TEXT_DOMAIN ),
    'ZSI' => __( 'Zamboanga Sibugay', WP_OFFICE_TEXT_DOMAIN ),
    '00'  => __( 'Metro Manila', WP_OFFICE_TEXT_DOMAIN ),
);
