<?php
/**
 * Turkey States
 */

if ( !defined( 'ABSPATH' ) ) {
    exit;
}

return array(
    'TR01' => __( 'Adana', WP_OFFICE_TEXT_DOMAIN ),
    'TR02' => __( 'Ad&#305;yaman', WP_OFFICE_TEXT_DOMAIN ),
    'TR03' => __( 'Afyon', WP_OFFICE_TEXT_DOMAIN ),
    'TR04' => __( 'A&#287;r&#305;', WP_OFFICE_TEXT_DOMAIN ),
    'TR05' => __( 'Amasya', WP_OFFICE_TEXT_DOMAIN ),
    'TR06' => __( 'Ankara', WP_OFFICE_TEXT_DOMAIN ),
    'TR07' => __( 'Antalya', WP_OFFICE_TEXT_DOMAIN ),
    'TR08' => __( 'Artvin', WP_OFFICE_TEXT_DOMAIN ),
    'TR09' => __( 'Ayd&#305;n', WP_OFFICE_TEXT_DOMAIN ),
    'TR10' => __( 'Bal&#305;kesir', WP_OFFICE_TEXT_DOMAIN ),
    'TR11' => __( 'Bilecik', WP_OFFICE_TEXT_DOMAIN ),
    'TR12' => __( 'Bing&#246;l', WP_OFFICE_TEXT_DOMAIN ),
    'TR13' => __( 'Bitlis', WP_OFFICE_TEXT_DOMAIN ),
    'TR14' => __( 'Bolu', WP_OFFICE_TEXT_DOMAIN ),
    'TR15' => __( 'Burdur', WP_OFFICE_TEXT_DOMAIN ),
    'TR16' => __( 'Bursa', WP_OFFICE_TEXT_DOMAIN ),
    'TR17' => __( '&#199;anakkale', WP_OFFICE_TEXT_DOMAIN ),
    'TR18' => __( '&#199;ank&#305;r&#305;', WP_OFFICE_TEXT_DOMAIN ),
    'TR19' => __( '&#199;orum', WP_OFFICE_TEXT_DOMAIN ),
    'TR20' => __( 'Denizli', WP_OFFICE_TEXT_DOMAIN ),
    'TR21' => __( 'Diyarbak&#305;r', WP_OFFICE_TEXT_DOMAIN ),
    'TR22' => __( 'Edirne', WP_OFFICE_TEXT_DOMAIN ),
    'TR23' => __( 'Elaz&#305;&#287;', WP_OFFICE_TEXT_DOMAIN ),
    'TR24' => __( 'Erzincan', WP_OFFICE_TEXT_DOMAIN ),
    'TR25' => __( 'Erzurum', WP_OFFICE_TEXT_DOMAIN ),
    'TR26' => __( 'Eski&#351;ehir', WP_OFFICE_TEXT_DOMAIN ),
    'TR27' => __( 'Gaziantep', WP_OFFICE_TEXT_DOMAIN ),
    'TR28' => __( 'Giresun', WP_OFFICE_TEXT_DOMAIN ),
    'TR29' => __( 'G&#252;m&#252;&#351;hane', WP_OFFICE_TEXT_DOMAIN ),
    'TR30' => __( 'Hakkari', WP_OFFICE_TEXT_DOMAIN ),
    'TR31' => __( 'Hatay', WP_OFFICE_TEXT_DOMAIN ),
    'TR32' => __( 'Isparta', WP_OFFICE_TEXT_DOMAIN ),
    'TR33' => __( '&#304;&#231;el', WP_OFFICE_TEXT_DOMAIN ),
    'TR34' => __( '&#304;stanbul', WP_OFFICE_TEXT_DOMAIN ),
    'TR35' => __( '&#304;zmir', WP_OFFICE_TEXT_DOMAIN ),
    'TR36' => __( 'Kars', WP_OFFICE_TEXT_DOMAIN ),
    'TR37' => __( 'Kastamonu', WP_OFFICE_TEXT_DOMAIN ),
    'TR38' => __( 'Kayseri', WP_OFFICE_TEXT_DOMAIN ),
    'TR39' => __( 'K&#305;rklareli', WP_OFFICE_TEXT_DOMAIN ),
    'TR40' => __( 'K&#305;r&#351;ehir', WP_OFFICE_TEXT_DOMAIN ),
    'TR41' => __( 'Kocaeli', WP_OFFICE_TEXT_DOMAIN ),
    'TR42' => __( 'Konya', WP_OFFICE_TEXT_DOMAIN ),
    'TR43' => __( 'K&#252;tahya', WP_OFFICE_TEXT_DOMAIN ),
    'TR44' => __( 'Malatya', WP_OFFICE_TEXT_DOMAIN ),
    'TR45' => __( 'Manisa', WP_OFFICE_TEXT_DOMAIN ),
    'TR46' => __( 'Kahramanmara&#351;', WP_OFFICE_TEXT_DOMAIN ),
    'TR47' => __( 'Mardin', WP_OFFICE_TEXT_DOMAIN ),
    'TR48' => __( 'Mu&#287;la', WP_OFFICE_TEXT_DOMAIN ),
    'TR49' => __( 'Mu&#351;', WP_OFFICE_TEXT_DOMAIN ),
    'TR50' => __( 'Nev&#351;ehir', WP_OFFICE_TEXT_DOMAIN ),
    'TR51' => __( 'Ni&#287;de', WP_OFFICE_TEXT_DOMAIN ),
    'TR52' => __( 'Ordu', WP_OFFICE_TEXT_DOMAIN ),
    'TR53' => __( 'Rize', WP_OFFICE_TEXT_DOMAIN ),
    'TR54' => __( 'Sakarya', WP_OFFICE_TEXT_DOMAIN ),
    'TR55' => __( 'Samsun', WP_OFFICE_TEXT_DOMAIN ),
    'TR56' => __( 'Siirt', WP_OFFICE_TEXT_DOMAIN ),
    'TR57' => __( 'Sinop', WP_OFFICE_TEXT_DOMAIN ),
    'TR58' => __( 'Sivas', WP_OFFICE_TEXT_DOMAIN ),
    'TR59' => __( 'Tekirda&#287;', WP_OFFICE_TEXT_DOMAIN ),
    'TR60' => __( 'Tokat', WP_OFFICE_TEXT_DOMAIN ),
    'TR61' => __( 'Trabzon', WP_OFFICE_TEXT_DOMAIN ),
    'TR62' => __( 'Tunceli', WP_OFFICE_TEXT_DOMAIN ),
    'TR63' => __( '&#350;anl&#305;urfa', WP_OFFICE_TEXT_DOMAIN ),
    'TR64' => __( 'U&#351;ak', WP_OFFICE_TEXT_DOMAIN ),
    'TR65' => __( 'Van', WP_OFFICE_TEXT_DOMAIN ),
    'TR66' => __( 'Yozgat', WP_OFFICE_TEXT_DOMAIN ),
    'TR67' => __( 'Zonguldak', WP_OFFICE_TEXT_DOMAIN ),
    'TR68' => __( 'Aksaray', WP_OFFICE_TEXT_DOMAIN ),
    'TR69' => __( 'Bayburt', WP_OFFICE_TEXT_DOMAIN ),
    'TR70' => __( 'Karaman', WP_OFFICE_TEXT_DOMAIN ),
    'TR71' => __( 'K&#305;r&#305;kkale', WP_OFFICE_TEXT_DOMAIN ),
    'TR72' => __( 'Batman', WP_OFFICE_TEXT_DOMAIN ),
    'TR73' => __( '&#350;&#305;rnak', WP_OFFICE_TEXT_DOMAIN ),
    'TR74' => __( 'Bart&#305;n', WP_OFFICE_TEXT_DOMAIN ),
    'TR75' => __( 'Ardahan', WP_OFFICE_TEXT_DOMAIN ),
    'TR76' => __( 'I&#287;d&#305;r', WP_OFFICE_TEXT_DOMAIN ),
    'TR77' => __( 'Yalova', WP_OFFICE_TEXT_DOMAIN ),
    'TR78' => __( 'Karab&#252;k', WP_OFFICE_TEXT_DOMAIN ),
    'TR79' => __( 'Kilis', WP_OFFICE_TEXT_DOMAIN ),
    'TR80' => __( 'Osmaniye', WP_OFFICE_TEXT_DOMAIN ),
    'TR81' => __( 'D&#252;zce', WP_OFFICE_TEXT_DOMAIN ),
);
