<?php
/**
 * United States
 */

if ( !defined( 'ABSPATH' ) ) {
    exit;
}

return array(
    'AL' => __( 'Alabama', WP_OFFICE_TEXT_DOMAIN ),
    'AK' => __( 'Alaska', WP_OFFICE_TEXT_DOMAIN ),
    'AZ' => __( 'Arizona', WP_OFFICE_TEXT_DOMAIN ),
    'AR' => __( 'Arkansas', WP_OFFICE_TEXT_DOMAIN ),
    'CA' => __( 'California', WP_OFFICE_TEXT_DOMAIN ),
    'CO' => __( 'Colorado', WP_OFFICE_TEXT_DOMAIN ),
    'CT' => __( 'Connecticut', WP_OFFICE_TEXT_DOMAIN ),
    'DE' => __( 'Delaware', WP_OFFICE_TEXT_DOMAIN ),
    'DC' => __( 'District Of Columbia', WP_OFFICE_TEXT_DOMAIN ),
    'FL' => __( 'Florida', WP_OFFICE_TEXT_DOMAIN ),
    'GA' => _x( 'Georgia', 'US state of Georgia', WP_OFFICE_TEXT_DOMAIN ),
    'HI' => __( 'Hawaii', WP_OFFICE_TEXT_DOMAIN ),
    'ID' => __( 'Idaho', WP_OFFICE_TEXT_DOMAIN ),
    'IL' => __( 'Illinois', WP_OFFICE_TEXT_DOMAIN ),
    'IN' => __( 'Indiana', WP_OFFICE_TEXT_DOMAIN ),
    'IA' => __( 'Iowa', WP_OFFICE_TEXT_DOMAIN ),
    'KS' => __( 'Kansas', WP_OFFICE_TEXT_DOMAIN ),
    'KY' => __( 'Kentucky', WP_OFFICE_TEXT_DOMAIN ),
    'LA' => __( 'Louisiana', WP_OFFICE_TEXT_DOMAIN ),
    'ME' => __( 'Maine', WP_OFFICE_TEXT_DOMAIN ),
    'MD' => __( 'Maryland', WP_OFFICE_TEXT_DOMAIN ),
    'MA' => __( 'Massachusetts', WP_OFFICE_TEXT_DOMAIN ),
    'MI' => __( 'Michigan', WP_OFFICE_TEXT_DOMAIN ),
    'MN' => __( 'Minnesota', WP_OFFICE_TEXT_DOMAIN ),
    'MS' => __( 'Mississippi', WP_OFFICE_TEXT_DOMAIN ),
    'MO' => __( 'Missouri', WP_OFFICE_TEXT_DOMAIN ),
    'MT' => __( 'Montana', WP_OFFICE_TEXT_DOMAIN ),
    'NE' => __( 'Nebraska', WP_OFFICE_TEXT_DOMAIN ),
    'NV' => __( 'Nevada', WP_OFFICE_TEXT_DOMAIN ),
    'NH' => __( 'New Hampshire', WP_OFFICE_TEXT_DOMAIN ),
    'NJ' => __( 'New Jersey', WP_OFFICE_TEXT_DOMAIN ),
    'NM' => __( 'New Mexico', WP_OFFICE_TEXT_DOMAIN ),
    'NY' => __( 'New York', WP_OFFICE_TEXT_DOMAIN ),
    'NC' => __( 'North Carolina', WP_OFFICE_TEXT_DOMAIN ),
    'ND' => __( 'North Dakota', WP_OFFICE_TEXT_DOMAIN ),
    'OH' => __( 'Ohio', WP_OFFICE_TEXT_DOMAIN ),
    'OK' => __( 'Oklahoma', WP_OFFICE_TEXT_DOMAIN ),
    'OR' => __( 'Oregon', WP_OFFICE_TEXT_DOMAIN ),
    'PA' => __( 'Pennsylvania', WP_OFFICE_TEXT_DOMAIN ),
    'RI' => __( 'Rhode Island', WP_OFFICE_TEXT_DOMAIN ),
    'SC' => __( 'South Carolina', WP_OFFICE_TEXT_DOMAIN ),
    'SD' => __( 'South Dakota', WP_OFFICE_TEXT_DOMAIN ),
    'TN' => __( 'Tennessee', WP_OFFICE_TEXT_DOMAIN ),
    'TX' => __( 'Texas', WP_OFFICE_TEXT_DOMAIN ),
    'UT' => __( 'Utah', WP_OFFICE_TEXT_DOMAIN ),
    'VT' => __( 'Vermont', WP_OFFICE_TEXT_DOMAIN ),
    'VA' => __( 'Virginia', WP_OFFICE_TEXT_DOMAIN ),
    'WA' => __( 'Washington', WP_OFFICE_TEXT_DOMAIN ),
    'WV' => __( 'West Virginia', WP_OFFICE_TEXT_DOMAIN ),
    'WI' => __( 'Wisconsin', WP_OFFICE_TEXT_DOMAIN ),
    'WY' => __( 'Wyoming', WP_OFFICE_TEXT_DOMAIN ),
    'AA' => __( 'Armed Forces (AA)', WP_OFFICE_TEXT_DOMAIN ),
    'AE' => __( 'Armed Forces (AE)', WP_OFFICE_TEXT_DOMAIN ),
    'AP' => __( 'Armed Forces (AP)', WP_OFFICE_TEXT_DOMAIN ),
);
